In [9]:
!pip install faiss-cpu requests

In [10]:
import faiss
import numpy as np
import requests

In [50]:
del index

In [51]:
dataset = [
    "Sudhanshu Kumar was born in Jamshedpur, Jharkhand, India, to a modest family.",
    "His early life was marked by financial hardship and limited resources.",
    "He believed education could transform his life and pursued it relentlessly.",
    "Sudhanshu earned a Computer Science and Engineering degree.",
    "He worked at Wipro, Deloitte, Verizon Labs, and Ernst & Young.",
    "He gained expertise in SAP WebDynpro, Fiori UI5 HANA, Java, Big Data, and Data Analytics.",
    "Sudhanshu remained committed to making education accessible for everyone.",
    "His teaching empowered countless students to build their careers.",
    "Many students credit him with changing their lives through affordable learning.",
    "His journey is a testament to triumph over adversity and the power of knowledge."
]


In [ ]:
# Generate embeddings with vector operations
import requests
import numpy as np
EURI_API_KEY= "euri-....."
def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {EURI_API_KEY}"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding


In [53]:
generate_embeddings("my name is sudhanshu kumar")

array([-0.00964424, -0.0254779 , -0.0277286 , ...,  0.00489808,
        0.0180506 , -0.00078423], shape=(1536,))

In [54]:
embeddings= []
for i in  dataset:
   emb = generate_embeddings(i)
   embeddings.append(emb)

In [55]:
embeddings

[array([-0.02541692, -0.01865577,  0.00634901, ..., -0.02143118,
         0.01235371,  0.00510738], shape=(1536,)),
 array([ 0.02540292, -0.0002544 ,  0.02801443, ..., -0.03046351,
        -0.0145695 , -0.00296451], shape=(1536,)),
 array([ 0.001587  , -0.01729287, -0.01732935, ..., -0.02582986,
        -0.01732935, -0.03174008], shape=(1536,)),
 array([-0.00452645, -0.01963622,  0.01436222, ..., -0.0424745 ,
         0.03230322,  0.00883512], shape=(1536,)),
 array([-0.03281466, -0.00356642,  0.017823  , ..., -0.01445926,
         0.01466496, -0.01732691], shape=(1536,)),
 array([-0.05149938,  0.00695922,  0.06715338, ..., -0.0353009 ,
         0.00894433, -0.0073449 ], shape=(1536,)),
 array([-0.00579057,  0.00271029,  0.04456783, ...,  0.0159549 ,
         0.00164392, -0.00090393], shape=(1536,)),
 array([ 0.04490583, -0.02969062,  0.02145419, ..., -0.04722387,
        -0.02574502, -0.01600433], shape=(1536,)),
 array([-0.02983718, -0.04339701,  0.00524785, ..., -0.00930332,
       

In [56]:
len(embeddings[0])

1536

In [57]:
embeddings_arrary = np.vstack(embeddings)

In [58]:
embeddings_arrary

array([[-0.02541692, -0.01865577,  0.00634901, ..., -0.02143118,
         0.01235371,  0.00510738],
       [ 0.02540292, -0.0002544 ,  0.02801443, ..., -0.03046351,
        -0.0145695 , -0.00296451],
       [ 0.001587  , -0.01729287, -0.01732935, ..., -0.02582986,
        -0.01732935, -0.03174008],
       ...,
       [ 0.04490583, -0.02969062,  0.02145419, ..., -0.04722387,
        -0.02574502, -0.01600433],
       [-0.02983718, -0.04339701,  0.00524785, ..., -0.00930332,
        -0.02247494,  0.0097054 ],
       [ 0.03265457, -0.00283638, -0.00402452, ...,  0.01120394,
        -0.05085592, -0.01056352]], shape=(10, 1536))

In [59]:
dimension = embeddings_arrary.shape[1]
index = faiss.IndexFlatL2(dimension)

In [60]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001DFB42196B0> >

In [61]:
index.add(embeddings_arrary)

In [62]:
index.ntotal

10

In [63]:
text = "my name is sudhanshu kumar i use to teach tech"

In [64]:
new_data = generate_embeddings(text).reshape(1,-1)

In [65]:
new_data

array([[-0.02793127, -0.0378635 , -0.01753267, ..., -0.00761934,
         0.01803684, -0.02036865]], shape=(1, 1536))

In [66]:
index.add(new_data)

In [67]:
index.ntotal

11

In [68]:
faiss.write_index(index,"sudhanshu_personal.faiss")

In [69]:
query = "who is sudhanshu kumar"

In [70]:
qeury_vec = generate_embeddings(query).reshape(1,-1)

In [71]:
qeury_vec

array([[-0.02782764, -0.02935768, -0.01452345, ...,  0.01749986,
         0.03294371,  0.00630545]], shape=(1, 1536))

In [82]:
distance , indices = index.search(qeury_vec ,6)

In [83]:
distance

array([[0.6484784 , 0.88970953, 0.96139395, 1.0492306 , 1.6094193 ,
        1.6728487 ]], dtype=float32)

In [84]:
indices

array([[ 0, 10,  3,  6,  5,  4]])

In [78]:
dataset[0]

'Sudhanshu Kumar was born in Jamshedpur, Jharkhand, India, to a modest family.'

In [85]:
dataset[3]

'Sudhanshu earned a Computer Science and Engineering degree.'

In [86]:
dataset[6]

'Sudhanshu remained committed to making education accessible for everyone.'