In [1]:
pip install pinecone

  Using cached pinecone_plugin_interface-0.0.7-py3-none-any.whl.metadata (1.2 kB)
   ---------------------------------------- 0.0/587.6 kB ? eta -:--:--
   --------------------------------------- 587.6/587.6 kB 20.3 MB/s eta 0:00:00
Using cached pinecone_plugin_interface-0.0.7-py3-none-any.whl (6.2 kB)
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [ ]:
from pinecone import Pinecone

PINECODE_API_kEY= "pcsk_........"

pc = Pinecone(api_key= PINECODE_API_kEY)
index = pc.Index("sudhanshuinfo")

c:\Users\scl\anaconda3\envs\assignment_grader\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
index

In [4]:
texts = [
    "Sudhanshu Kumar was born in Jamshedpur, Jharkhand, India, to a modest family.",
    "His early life was marked by financial hardship and limited resources.",
    "He believed education could transform his life and pursued it relentlessly.",
    "Sudhanshu earned a Computer Science and Engineering degree.",
    "He worked at Wipro, Deloitte, Verizon Labs, and Ernst & Young.",
    "He gained expertise in SAP WebDynpro, Fiori UI5 HANA, Java, Big Data, and Data Analytics.",
    "Sudhanshu remained committed to making education accessible for everyone.",
    "His teaching empowered countless students to build their careers.",
    "Many students credit him with changing their lives through affordable learning.",
    "His journey is a testament to triumph over adversity and the power of knowledge."
]


In [ ]:
# Generate embeddings with vector operations
import requests
import numpy as np
EURI_API_KEY= "euri-..."

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {EURI_API_KEY}"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    # Convert to numpy array for vector operations
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [6]:
embeddings = [generate_embeddings(i) for i in texts]

In [7]:
embeddings

[array([-0.0248889 , -0.02120667,  0.00471491, ..., -0.0209146 ,
         0.01101537,  0.00508001], shape=(1536,)),
 array([ 0.02542444, -0.00025488,  0.02802438, ..., -0.03042432,
        -0.01457468, -0.00296243], shape=(1536,)),
 array([ 0.00161294, -0.01728175, -0.01731823, ..., -0.02583141,
        -0.01733039, -0.03171766], shape=(1536,)),
 array([-0.00452645, -0.01963622,  0.01436222, ..., -0.0424745 ,
         0.03230322,  0.00883512], shape=(1536,)),
 array([-0.03273299, -0.00337793,  0.01825354, ..., -0.01453993,
         0.01478186, -0.01734631], shape=(1536,)),
 array([-0.05149938,  0.00695922,  0.06715338, ..., -0.0353009 ,
         0.00894433, -0.0073449 ], shape=(1536,)),
 array([-0.00579057,  0.00271029,  0.04456783, ...,  0.0159549 ,
         0.00164392, -0.00090393], shape=(1536,)),
 array([ 0.04490583, -0.02969062,  0.02145419, ..., -0.04722387,
        -0.02574502, -0.01600433], shape=(1536,)),
 array([-0.02980111, -0.04341259,  0.00523252, ..., -0.00930765,
       

In [12]:
index.upsert(
    vectors=[(
        "0",
        embeddings[0].tolist(),
        {'text' : texts[0]})
    ]
)

{'upserted_count': 1}

In [13]:
records = []
for i , (text,emb) in enumerate(zip(texts,embeddings)):
    records.append(
        (
            f'rec_{i})',
            emb.tolist(),
            {'text':text}
        )
    )
    

In [14]:
records

[('rec_0)',
  [-0.024888895,
   -0.021206673,
   0.0047149123,
   0.018578006,
   0.0033718925,
   0.0052990606,
   0.023324212,
   0.029666394,
   0.0044854255,
   -0.033859745,
   0.008266743,
   -0.03031313,
   -0.017284535,
   -0.015991064,
   0.033400774,
   0.014541123,
   0.025598219,
   -0.06951366,
   -0.00032141202,
   0.012527897,
   0.07581412,
   0.0011356992,
   0.02186384,
   -0.015865888,
   0.0368848,
   -0.013956975,
   -0.053240955,
   -0.039888993,
   -0.014176031,
   -0.04994469,
   -0.023011275,
   0.0015972808,
   0.0042011747,
   -0.01134917,
   0.025034932,
   -0.019193448,
   -0.00964888,
   0.010702434,
   -0.0069941343,
   -0.0058362684,
   -0.019579403,
   -0.05908244,
   -0.02280265,
   0.04548013,
   -0.018317226,
   0.020080103,
   -0.0056902315,
   0.02518097,
   -0.04969434,
   -0.0054190196,
   -0.00793816,
   -0.020132259,
   0.061919734,
   -0.00044854253,
   0.008798735,
   -0.008715286,
   0.01570942,
   0.0278305,
   -0.0042272527,
   -0.03930484

In [15]:
index.upsert(vectors=records)

{'upserted_count': 10}

In [16]:
index.describe_index_stats()

{'dimension': 1536,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 11}},
 'total_vector_count': 11,
 'vector_type': 'dense'}

In [17]:
index.fetch(ids=['rec_3'])

FetchResponse(namespace='', vectors={}, usage={'read_units': 1})

In [20]:
query = "sudhanshu has worked in wipro"

In [28]:
query_embed = generate_embeddings(query).tolist()

RESPONSE: {'object': 'list', 'data': [{'object': 'embedding', 'embedding': [-0.064057335, -0.017189814, 0.06668636, -0.005027388, -0.012601649, -0.027554259, 0.0016668431, 0.06764697, -0.0054318546, -0.05237837, 0.011186018, -0.03716033, -0.068253666, -0.024369089, 0.056423035, 0.006939123, -0.006209188, -0.052226696, -0.04426377, 0.012127666, 0.03276176, 0.06173165, 0.011887514, 0.00703392, 0.022675386, -0.043530673, -0.06117551, -0.002259323, 0.017126616, -0.014598701, -0.033570696, -0.021221835, 0.029526033, 0.025911115, 0.019376459, -5.1644485e-05, 0.011198658, 0.05389512, -0.0047113993, 0.00019433336, -0.034152113, -0.0187824, 0.008872977, 0.003599117, 0.004158418, -0.013296826, -0.04474407, 0.030259127, -0.014674539, -0.018377932, 0.00704024, -0.019679809, 0.038525406, 0.027554259, -0.041028038, -0.0146619, 0.034152113, 0.05571522, -0.012367818, -0.043758187, 0.02603751, 0.00292922, 0.062035, -0.0011817997, -0.012412056, -0.01348642, -0.013979362, 0.00051743235, -0.009732468, -0.

In [ ]:
def generate_embeddings(text):
    import requests
    import numpy as np

    url = "https://api.euron.one/api/v1/euri/alpha/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {EURI_API_KEY}"
    }
    payload = {
        "model": "text-embedding-3-small",
        "input": text
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    print("RESPONSE:", data)

    if "error" in data:
        raise ValueError(f"Embedding API error: {data['error']}")

    if "data" not in data:
        raise ValueError("No 'data' field in response. Got: " + str(data))

    embedding = np.array(data["data"][0]["embedding"])
    return embedding


In [29]:
query

'sudhanshu has worked in wipro'

In [30]:
query_embed

[-0.064057335,
 -0.017189814,
 0.06668636,
 -0.005027388,
 -0.012601649,
 -0.027554259,
 0.0016668431,
 0.06764697,
 -0.0054318546,
 -0.05237837,
 0.011186018,
 -0.03716033,
 -0.068253666,
 -0.024369089,
 0.056423035,
 0.006939123,
 -0.006209188,
 -0.052226696,
 -0.04426377,
 0.012127666,
 0.03276176,
 0.06173165,
 0.011887514,
 0.00703392,
 0.022675386,
 -0.043530673,
 -0.06117551,
 -0.002259323,
 0.017126616,
 -0.014598701,
 -0.033570696,
 -0.021221835,
 0.029526033,
 0.025911115,
 0.019376459,
 -5.1644485e-05,
 0.011198658,
 0.05389512,
 -0.0047113993,
 0.00019433336,
 -0.034152113,
 -0.0187824,
 0.008872977,
 0.003599117,
 0.004158418,
 -0.013296826,
 -0.04474407,
 0.030259127,
 -0.014674539,
 -0.018377932,
 0.00704024,
 -0.019679809,
 0.038525406,
 0.027554259,
 -0.041028038,
 -0.0146619,
 0.034152113,
 0.05571522,
 -0.012367818,
 -0.043758187,
 0.02603751,
 0.00292922,
 0.062035,
 -0.0011817997,
 -0.012412056,
 -0.01348642,
 -0.013979362,
 0.00051743235,
 -0.009732468,
 -0.025367

In [31]:
index.query(
    vector=query_embed,
    top_k=2,
    include_metadata=True
)

{'matches': [{'id': 'rec_4)',
              'metadata': {'text': 'He worked at Wipro, Deloitte, Verizon '
                                   'Labs, and Ernst & Young.'},
              'score': 0.582195163,
              'values': []},
             {'id': 'rec_3)',
              'metadata': {'text': 'Sudhanshu earned a Computer Science and '
                                   'Engineering degree.'},
              'score': 0.578928888,
              'values': []}],
 'namespace': '',
 'usage': {'read_units': 6}}

In [32]:
query

'sudhanshu has worked in wipro'